INSERT INTO usuarios (usuario, password, nombre_usuario, no_credencial, permisos) VALUES ('jleal0', 'nicol8899', 'Jorge Marco vinicio Leal Villagran Aquilar', 27000268, 'Cat1-T|Nom-T|Est-T');
INSERT INTO usuarios (usuario, password, nombre_usuario, no_credencial, permisos) VALUES ('hirfra0', 'nicol8899', 'Hirlando Franco Sanchez', 27002035, 'Cat1-T|Nom-T|Est-T');
INSERT INTO usuarios (usuario, password, nombre_usuario, no_credencial, permisos) VALUES ('sramirez0', 'nicol8899', 'Silvia ramirez Morales', 27000685, 'Cat1-T|Nom-T|Est-T');
INSERT INTO TiposEstaSAT (descripcion, id_usuario) VALUES (' Recibido', 1);
INSERT INTO TiposEstaSAT (descripcion, id_usuario) VALUES ('En Proceso', 1);
INSERT INTO TiposEstaSAT (descripcion, id_usuario) VALUES ('Timbrado', 1);
INSERT INTO TipoNomina (descripcion, id_usuario) VALUES ('Nomina Ordinaria Quincena 1', 1);
INSERT INTO TipoNomina (descripcion, id_usuario) VALUES ('Nomina Ordinaria Quincena 2', 1);
INSERT INTO TipoNomina (descripcion, id_usuario) VALUES ('Nomina extraordinaria', 1);
INSERT INTO TipoNomina (descripcion, id_usuario) VALUES ('Nomina de aguinaldo parte 1', 1);
INSERT INTO TipoNomina (descripcion, id_usuario) VALUES ('Nomina de aquinaldo parte 2', 1);
INSERT INTO TipoNomina (descripcion, id_usuario) VALUES ('Nomina de Retroactivo', 1);
INSERT INTO TipoNomina (descripcion, id_usuario) VALUES ('Nomina especial 1', 1);
INSERT INTO TipoNomina (descripcion, id_usuario) VALUES ('Nomina especial 2', 1);
INSERT INTO TipDivision (descripcion, id_usuario) VALUES ('SABG', 1);
INSERT INTO TipDivision (descripcion, id_usuario) VALUES ('OTP', 1);
INSERT INTO Tip_EstNom (descripcion, id_usuario) VALUES ('Pagado', 1);
INSERT INTO Tip_EstNom (descripcion, id_usuario) VALUES ('Cancelado', 1);
INSERT INTO TipoParam (descripcion, id_usuario) VALUES ('Blob Azure', 1);
INSERT INTO TipoParam (descripcion, id_usuario) VALUES ('Web Service SAT', 1);
INSERT INTO TipoParam (descripcion, id_usuario) VALUES ('Sello digital', 1);
INSERT INTO TipoParam (descripcion, id_usuario) VALUES ('Coneccion base de datos', 1);
INSERT INTO Parametros (id_tiparam, id_usuario, id_division, clave, valor, fecha_inic, fecha_fin, descripcion) VALUES (1, 1, 1, 'qqqq', 'qqqq', '2026-02-27 00:00:00', '2026-02-27 00:00:00', 'wwww');
INSERT INTO Parametros (id_tiparam, id_usuario, id_division, clave, valor, fecha_inic, fecha_fin, descripcion) VALUES (1, 1, 1, 'Uri', 'https://cfdinominastorage.blob.core.windows.net', '2026-02-26 00:00:00', '9999-02-26 00:00:00', ' Contiene la url del blob de almacenamiento');
INSERT INTO Parametros (id_tiparam, id_usuario, id_division, clave, valor, fecha_inic, fecha_fin, descripcion) VALUES (1, 1, 1, 'StorageCredentialsAccount', 'sv=2018-03-28&sr=c&si=ReadWrite&sig=pb%2FLZnYNXO8g36AkymYztZ2kW%2FzPzTy0U6u3sYVVd2U%3D', '2026-02-26 00:00:00', '9999-02-26 00:00:00', 'Contiene el acount de acceso al blob');
INSERT INTO Parametros (id_tiparam, id_usuario, id_division, clave, valor, fecha_inic, fecha_fin, descripcion) VALUES (1, 1, 1, 'StorageCredentialsAndKey', '12345678a ', '2026-02-26 00:00:00', '9999-02-26 00:00:00', 'Password del acceso al blob');
INSERT INTO Parametros (id_tiparam, id_usuario, id_division, clave, valor, fecha_inic, fecha_fin, descripcion) VALUES (1, 1, 1, 'ContainerReference', 'contenedorarchivossfp941229ima', '2026-02-26 00:00:00', '9999-02-26 00:00:00', ' Contenedor de referencia');
INSERT INTO Parametros (id_tiparam, id_usuario, id_division, clave, valor, fecha_inic, fecha_fin, descripcion) VALUES (1, 1, 1, 'BlobReference', 'paqueterecepcion.zip', '2026-02-26 00:00:00', '9999-02-26 00:00:00', ' Es posible que este no se use');
INSERT INTO Parametros (id_tiparam, id_usuario, id_division, clave, valor, fecha_inic, fecha_fin, descripcion) VALUES (1, 1, 1, 'HuellaFiel', '0E1C75FB3EF5E773127357212CD6C85F842114CC', '2026-02-26 00:00:00', '9999-02-26 00:00:00', '  Huella del certificado de la Fiel de utenticacio');
