01|ArchExcel|C:/Users/jleal/Documents/AAAA_Trabajo/CFDI_CSHARP/BaseDatos/ArchivosExcel/DatosCatalogosOriginales.xlsx
01|DirSal|C:/Users/jleal/Documents/AAAA_Trabajo/CFDI_CSHARP/BaseDatos/ArchivosSQL
02|DirEnt|C:/Users/jleal/Documents/AAAA_Trabajo/CFDI_CSHARP/BaseDatos/ArchivosSQL
02|ChekLog|Si
02|NomLog|Opera01
01|Tablas|Usuarios,TipoNomina,TipoEstaSAT,TipoEstNom,TipoDivision,TipoParam,TipoPermiso,TipAlcance,Parametros,PerUsuario
02|Querys|Ins_TipAlcance,Ins_TipoDivision,Ins_TipoEstNom,Ins_TipoEstaSAT,Ins_TipoNomina,Ins_TipoParam,Ins_TipoPermiso,Ins_Usuarios
